### ISSUE TITLE
API Support for closest parent network

### ISSUE THREAD

**Issue by coxley** [dropbox/nsot#171]
While shouldn't be the default, I would like to see an option for searching for the closest parent network. In my case, most users expect when searching for `10.250.0.1` to get the info for `10.250.0.0/24` or `10.250.0.0/16` and so on.

I have a couple workarounds in some apps which if given a `/32`, try for every length `range(32)` until ultimately saying sorry. Obviously this is quite slow if the closest result is a /8 or nonexistent altogether.

From an API perspective, I see this usecase similar to `/subnets` and `/supernets`: `GET /sites/1/networks/10.250.0.1/32/recurse`

**Comment by gmjosack** [comment]
Is this different from `networks/{pk}/parent/` and/or `networks/{pk}/ancestors/`?

**Comment by coxley** [comment]
It's different in that the resource has to exist to use ``parent`` or ``ancestors``. It's quite tough to always have every possible /32 registered as a resource in NSoT, but still want to be able to get general metadata.

**Comment by gmjosack** [comment]
Makes sense. Thanks for clarifying!

**Comment by jathanism** [comment]
I don't think this would be too difficult to implement. I'd rather name it something obvious like `networks/{pk}/closest_parent/`.

**Comment by jathanism** [comment]
Meh, forget what I said. It's actually easier to implement it the other way around.
