### ISSUE TITLE
Possible Feature: Circuits

### ISSUE THREAD

**Issue by coxley** [dropbox/nsot#203]
Circuits are a feature many want in network inventory, so eventually we should provide this to them. `a_endpoint` and `z_endpoint` could be refs to existing `interface` objects.

**Comment by jathanism** [comment]
This is an important idea and was a core motivating factor in the design of the Interface objects. 

One thing to consider is what it is that makes a circuit, and that is two interfaces connected by a point-to-point link. For example:

- Define a p2p network: 10.10.10.0/31
- Assign an IP address from that network on Interface A (local): 10.10.10.1/32
- Assign an IP address form that network on Interface Z (remote): 10.10.10.2/32
- You now have an adjacency between two interfaces on either side of a p2p link: AKA a circuit.

If this assertion is correct, I'd like to think about how to formalize it in a meaningful way.

**Comment by coxley** [comment]
I don't think it can be asserted that everyone uses /31's for p2p (only because I've been places where they don't).

One thing to think about is how to represent both a circuit between gear that you own and third party gear. Should it be asserted that the third party end also have an interface object? That might get weird since it'd then have to have a device object which might not be meaningful since you won't always know what's at the other end.

**Comment by jathanism** [comment]
@coxley When you're right you're right. What if instead of assuming it's a /32, it's just tagged in a certain way? Or do you think it still needs to be a concrete object relationship instead?

**Comment by coxley** [comment]
@jathanism: If a solo-interface is just tagged `link_type=p2p`, you can't fetch a Z side. I still think that part is important, but I'm not sure how to go about representing something 3rd party (transit, public peering, PNI) without having a device object for them.

Maybe a circuit should be it's own resource type where `a_endpoint` MUST be existing interface resource and `z_endpoint` MAY be existing interface and otherwise a custom structure? I don't know fully.

**Comment by coxley** [comment]
I think it's acceptable to have `z_endpoint` be a reference to interface or otherwise `null`. It's what we do for internal modeling.

To summarize:

* Circuit Resource
* a-side reference (required)
* z-side reference (optional)
* If Locations become their own resource, a and z location references

**Comment by coxley** [comment]
Oh, another thing is Circuit type. Peering, internal, transit, etc. But since it's kinda specific to different types of networks and may change, it's probably better left to user to just create a Circuit attribute with choices.
