### ISSUE TITLE
dropbox/nsot Does not exist in public docker hub

### ISSUE THREAD

**Issue by allanice001** [dropbox/nsot#238]
dropbox/nsot Does not exist in public docker hub

Can you guys create an upstream image / allow one of the community members to do so?

I have one based off your dockerfile (http://nsot.readthedocs.io/en/latest/dockerfile.html)

https://hub.docker.com/r/infrascloudy/nsot

**Comment by jathanism** [comment]
Thanks for reporting this. The `Dockerfile` was implemented by @coxley and I haven't had much hands-on w/ it myself unfortunately as we don't use containers in prod (yet) at Dropbox...

I'd love to formally register dropbox/nsot on Docker hub, I just don't have any experience with it.

**Comment by jathanism** [comment]
Fixed in #239 and #241
