### ISSUE TITLE
 Implement natural keys as primary keys for related fields

### ISSUE THREAD

**Issue by jathanism** [dropbox/nsot#262]
This is so that any objects that support natural keys can also use these values as primary keys in the API when creating/updating related fields. For example:

- `Interface(name='ae0.0', device='foo1-br01', parent='foo1-br01:ae0')` 
- `Circuit(endpoint_a='foo1-br01:ae0', endpoint_z='bar1-bb01:ae0')`  
- etc.

This will facilitate more user-friendly object payloads as well as allowing the CLI interaction by humans to be much more intuitive and not rely so heavily upon numeric object IDs.

**Comment by yeled** [comment]
This would be amazing, and allow much easier integration with scripts etc.
