### ISSUE TITLE
Changes always links to first site

### ISSUE THREAD

**Issue by jathanism** [dropbox/nsot#51]
No matter which site you select (such as if you have multiple sites e.g. /sites/1, /sites/2), the link for "Changes" is always "/sites/1/changes"

**Comment by jathanism** [comment]
Hard-coded here: https://github.com/dropbox/nsot/blob/master/nsot/templates/app.html#L64

**Comment by gmjosack** [comment]
Fixed in 64615c2a5b9b2357b819f4f00ed4090004868e1e
