### ISSUE TITLE
Documentation: Intro.rst

### ISSUE THREAD

**Issue by coxley** [dropbox/nsot#58]
```rst
There are currently three types of permissions a User
can have in order to make modifications:

    * admin
        - Ability to Update/Delete Site
        - Ability to grant permissions within a site
        - All subsequent permissions
    * networks
        - Ability to Add/Update/Delete Networks
        - Ability to Add/Update/Delete Attributes for Networks.
```
**Three** types of permissions user can have, two described.

**Comment by gmjosack** [comment]
This is a documentation bug. We simplified the permissions to just `admin` which gives full write permissions to simplify the permission model until we had a better feel for how we'd want to design it. 

Thanks for the report! We'll get the doc cleaned up.

**Comment by coxley** [comment]
Cool, thanks!

**Comment by jathanism** [comment]
Reopening so that we can get this fixed. :)
