### ISSUE TITLE
Support for regex-based attribute lookups via the API

### ISSUE THREAD

**Issue by fach** [dropbox/nsot#82]
While set unions allow for an enumerated query of multiple values of the same attribute key, it would be useful if a regex could be passed via the client api as well:

set union-based query (current implementation):
```
nsot.devices.query.get(query='facility=iad1 +facility=iad3 +facility=iad4 role=pr +role=br +role=dr')
```
vs. regex-based query (proposed):
```
nsot.devices.query.get(query='facility_regex=iad[134] role_regex=[pbd]r')
```

**Comment by jathanism** [comment]
This should be implemented in the API first, and then we can build this support into the pynsot client.

**Comment by jathanism** [comment]
We should be able to implement this pretty easily using a DRF regex search filter:

http://www.django-rest-framework.org/api-guide/filtering/#searchfilter
